title: "[Idea]: "
labels: ["idea"]
body:
  - type: markdown
    attributes:
      value: |
        **Got an idea for the repository or a new RAG technique?**
        Share it here! We love to hear about new papers, tools, or architectural patterns.
  - type: textarea
    id: idea
    attributes:
      label: Idea Description
      description: What's on your mind?
      placeholder: "We should add a section for 'RAG with Vision Models'..."
    validations:
      required: true
