title: "[Q&A]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        **Have a question about RAG in production?**
        Ask the community here! Whether it's about vector DB selection, latency optimization, or retrieval strategies.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is your question?
      placeholder: "How do I handle multi-hop retrieval efficiently?"
    validations:
      required: true
