name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Got an idea?**
        We'd love to hear how we can improve.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature or problem it solves.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: "It would be great if..."
    validations:
      required: true
